version: '3'

services:

  db:
    image: postgres
    restart: unless-stopped
    command: postgres -c listen_addresses='*'
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Berlin

      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

      - POSTGRES_DB=testdb
      
  phppgadmin:
    build: .
    image: ghcr.io/servercontainers/phppgadmin
    restart: unless-stopped
    environment: 
      - TZ=Europe/Berlin

      - DISABLE_TLS=disable

      - DB_HOST=db
    ports: 
      - 8080:80
    links:
      - "db:db"
    depends_on:
      - db    
